import type { User, PremiumSubscription } from "@/types";

// ─── Dashboard Stats ─────────────────────────────────────────────────────────

export const dashboardStats = {
  totalUsers: 12456,
  activeUsers: 8234,
  inactiveUsers: 4222,
  premiumUsers: 2845,
};

// ─── Monthly User Growth Chart ───────────────────────────────────────────────

export const monthlyUserGrowthData = [
  { month: "Jan", users: 38 },
  { month: "Feb", users: 32 },
  { month: "Mar", users: 52 },
  { month: "Apr", users: 46 },
  { month: "May", users: 62 },
  { month: "Jun", users: 68 },
  { month: "July", users: 80 },
  { month: "Aug", users: 85 },
  { month: "Sep", users: 78 },
  { month: "Oct", users: 72 },
  { month: "Nov", users: 82 },
  { month: "Dec", users: 92 },
];

// ─── Premium Users by Product Chart ─────────────────────────────────────────

export const premiumByProductData = [
  { name: "Matura", value: 124, color: "#3B82F6" },
  { name: "Medicine", value: 98, color: "#8B5CF6" },
  { name: "Law Entrance", value: 75, color: "#06B6D4" },
  { name: "Economics Entrance", value: 62, color: "#F59E0B" },
  { name: "Semimatura", value: 44, color: "#10B981" },
  { name: "Other Topics", value: 30, color: "#6366F1" },
  { name: "Architecture", value: 18, color: "#EF4444" },
];

// ─── Category Distribution ───────────────────────────────────────────────────

export const categoryDistributionData = [
  { name: "Matura", value: 5840, color: "#3B82F6" },
  { name: "Entrance Exams", value: 4320, color: "#6366F1" },
  { name: "Semimatura", value: 3000, color: "#06B6D4" },
];

// ─── Platform Content Summary ─────────────────────────────────────────────────

export const platformContentStats = [
  { label: "Total Questions", value: "8,642", change: "+523 this month", icon: "help-circle" },
  { label: "Total Tests", value: "246", change: "+12 new tests", icon: "file-check" },
  { label: "Draft Questions", value: "184", change: "+43 pending review", icon: "file-edit" },
  { label: "Blog Posts", value: "67", change: "+6 this week", icon: "newspaper" },
  { label: "Marketplace Products", value: "38", change: "+3 new listings", icon: "shopping-bag" },
];

// ─── Content Alerts ───────────────────────────────────────────────────────────

export const contentAlerts = [
  {
    id: "1",
    type: "warning",
    title: "Draft questions pending",
    description: "42 questions in draft status need review",
  },
  {
    id: "2",
    type: "error",
    title: "Tests missing answers",
    description: "5 tests have incomplete answer keys",
  },
  {
    id: "3",
    type: "info",
    title: "New marketplace listings",
    description: "3 products are awaiting approval",
  },
];

// ─── Recent Users (Overview) ──────────────────────────────────────────────────

export const recentUsersData = [
  {
    id: "r1",
    initials: "AB",
    name: "Arta Berisha",
    email: "arta.b@email.com",
    category: "Matura",
    activePlan: "Matura Pack",
    lastActivity: "Feb 15, 2026",
    joinedDate: "Feb 15, 2026",
    status: "Active" as const,
  },
  {
    id: "r2",
    initials: "DH",
    name: "Dritan Hoxha",
    email: "dritan.h@email.com",
    category: "Semimatura",
    activePlan: "Semimatura Pack",
    lastActivity: "Feb 15, 2026",
    joinedDate: "Feb 15, 2026",
    status: "Suspended" as const,
  },
  {
    id: "r3",
    initials: "EK",
    name: "Elona Krasniqi",
    email: "elona.k@email.com",
    category: "Matura",
    activePlan: "Free",
    lastActivity: "Feb 15, 2026",
    joinedDate: "Feb 15, 2026",
    status: "Active" as const,
  },
  {
    id: "r4",
    initials: "FG",
    name: "Fatos Gashi",
    email: "fatos.g@email.com",
    category: "Entrance Exams",
    activePlan: "Medicine Entrance",
    lastActivity: "Feb 15, 2026",
    joinedDate: "Feb 15, 2026",
    status: "Suspended" as const,
  },
  {
    id: "r5",
    initials: "GS",
    name: "Genta Shehu",
    email: "genta.s@email.com",
    category: "Entrance Exams",
    activePlan: "Medicine Entrance",
    lastActivity: "Feb 15, 2026",
    joinedDate: "Feb 15, 2026",
    status: "Suspended" as const,
  },
  {
    id: "r6",
    initials: "IM",
    name: "Ilir Maloku",
    email: "ilir.m@email.com",
    category: "Entrance Exams",
    activePlan: "Free",
    lastActivity: "Feb 15, 2026",
    joinedDate: "Feb 15, 2026",
    status: "Suspended" as const,
  },
];

// ─── Full Users List (User Management) ───────────────────────────────────────

export const mockUsers: User[] = [
  {
    id: "1",
    initials: "AB",
    name: "Arta Berisha",
    email: "arta.b@email.com",
    phone: "+355 69 234 5678",
    category: "Matura",
    activePlan: "Matura Pack",
    lastActivity: "2 hours ago",
    joinedDate: "Sep 12, 2025",
    status: "Active",
    planDate: "Jan 15, 2026",
    planExpiration: "Jul 15, 2026",
    completedQuizzes: 84,
    averageScore: 78,
    lastLogin: "Mar 9, 2026",
    role: "student",
    createdAt: "2025-09-12",
    updatedAt: "2026-03-09",
  },
  {
    id: "2",
    initials: "DH",
    name: "Dritan Hoxha",
    email: "dritan.h@email.com",
    phone: "+355 68 345 6789",
    category: "Entrance Exams",
    activePlan: "Medicine Entrance",
    lastActivity: "5 hours ago",
    joinedDate: "Oct 3, 2025",
    status: "Active",
    planDate: "Feb 1, 2026",
    planExpiration: "Aug 1, 2026",
    completedQuizzes: 56,
    averageScore: 72,
    lastLogin: "Mar 12, 2026",
    role: "student",
    createdAt: "2025-10-03",
    updatedAt: "2026-03-12",
  },
  {
    id: "3",
    initials: "EK",
    name: "Elona Krasniqi",
    email: "elona.k@email.com",
    phone: "+383 44 567 890",
    category: "Semimatura",
    activePlan: "Semimatura Pack",
    lastActivity: "1 day ago",
    joinedDate: "Aug 20, 2025",
    status: "Active",
    planDate: "Dec 10, 2025",
    planExpiration: "Dec 10, 2026",
    completedQuizzes: 102,
    averageScore: 85,
    lastLogin: "Mar 11, 2026",
    role: "student",
    createdAt: "2025-08-20",
    updatedAt: "2026-03-11",
  },
  {
    id: "4",
    initials: "FG",
    name: "Fatos Gashi",
    email: "fatos.g@email.com",
    phone: "+383 45 678 901",
    category: "Entrance Exams",
    activePlan: "Law Entrance",
    lastActivity: "3 days ago",
    joinedDate: "Jul 15, 2025",
    status: "Suspended",
    planDate: "Nov 5, 2025",
    planExpiration: "Mar 5, 2026",
    completedQuizzes: 23,
    averageScore: 55,
    lastLogin: "Mar 9, 2026",
    role: "student",
    createdAt: "2025-07-15",
    updatedAt: "2026-03-09",
  },
  {
    id: "5",
    initials: "GS",
    name: "Genta Shehu",
    email: "genta.s@email.com",
    phone: "+355 69 789 012",
    category: "Matura",
    activePlan: "Matura Pack",
    lastActivity: "6 hours ago",
    joinedDate: "Nov 8, 2025",
    status: "Active",
    planDate: "Jan 20, 2026",
    planExpiration: "Jan 20, 2027",
    completedQuizzes: 67,
    averageScore: 81,
    lastLogin: "Mar 12, 2026",
    role: "student",
    createdAt: "2025-11-08",
    updatedAt: "2026-03-12",
  },
  {
    id: "6",
    initials: "IM",
    name: "Ilir Maloku",
    email: "ilir.m@email.com",
    phone: "+383 44 890 123",
    category: "Entrance Exams",
    activePlan: "Free",
    lastActivity: "7 days ago",
    joinedDate: "Dec 1, 2025",
    status: "Inactive",
    planDate: "—",
    planExpiration: "—",
    completedQuizzes: 8,
    averageScore: 60,
    lastLogin: "Mar 5, 2026",
    role: "student",
    createdAt: "2025-12-01",
    updatedAt: "2026-03-05",
  },
  {
    id: "7",
    initials: "JB",
    name: "Jetmira Beka",
    email: "jetmira.b@email.com",
    phone: "+355 68 901 234",
    category: "Matura",
    activePlan: "Free",
    lastActivity: "12 hours ago",
    joinedDate: "Jan 5, 2026",
    status: "Active",
    planDate: "—",
    planExpiration: "—",
    completedQuizzes: 15,
    averageScore: 70,
    lastLogin: "Mar 12, 2026",
    role: "student",
    createdAt: "2026-01-05",
    updatedAt: "2026-03-12",
  },
  {
    id: "8",
    initials: "KR",
    name: "Kushtrim Rexhep",
    email: "kushtrim.r@email.com",
    phone: "+383 45 012 345",
    category: "Entrance Exams",
    activePlan: "Economics Entrance",
    lastActivity: "1 day ago",
    joinedDate: "Oct 22, 2025",
    status: "Active",
    planDate: "Feb 15, 2026",
    planExpiration: "Aug 15, 2026",
    completedQuizzes: 44,
    averageScore: 77,
    lastLogin: "Mar 11, 2026",
    role: "student",
    createdAt: "2025-10-22",
    updatedAt: "2026-03-11",
  },
  {
    id: "9",
    initials: "LM",
    name: "Lindita Maliqi",
    email: "lindita.m@email.com",
    phone: "+355 69 123 456",
    category: "Semimatura",
    activePlan: "Semimatura Pack",
    lastActivity: "4 hours ago",
    joinedDate: "Sep 30, 2025",
    status: "Active",
    planDate: "Sep 1, 2025",
    planExpiration: "Sep 1, 2026",
    completedQuizzes: 91,
    averageScore: 88,
    lastLogin: "Mar 12, 2026",
    role: "student",
    createdAt: "2025-09-30",
    updatedAt: "2026-03-12",
  },
  {
    id: "10",
    initials: "MT",
    name: "Mergim Thaqi",
    email: "mergim.t@email.com",
    phone: "+383 44 234 567",
    category: "Entrance Exams",
    activePlan: "Medicine Entrance",
    lastActivity: "30 min ago",
    joinedDate: "Feb 14, 2026",
    status: "Active",
    planDate: "Mar 1, 2026",
    planExpiration: "Sep 1, 2026",
    completedQuizzes: 12,
    averageScore: 75,
    lastLogin: "Mar 12, 2026",
    role: "student",
    createdAt: "2026-02-14",
    updatedAt: "2026-03-12",
  },
  {
    id: "11",
    initials: "NB",
    name: "Nora Berisha",
    email: "nora.b@email.com",
    phone: "+355 68 345 678",
    category: "Matura",
    activePlan: "Matura Pack",
    lastActivity: "2 days ago",
    joinedDate: "Jul 20, 2025",
    status: "Active",
    planDate: "Jul 20, 2025",
    planExpiration: "Jul 20, 2026",
    completedQuizzes: 120,
    averageScore: 91,
    lastLogin: "Mar 10, 2026",
    role: "student",
    createdAt: "2025-07-20",
    updatedAt: "2026-03-10",
  },
  {
    id: "12",
    initials: "RK",
    name: "Rinor Kelmendi",
    email: "rinor.k@email.com",
    phone: "+383 45 456 789",
    category: "Entrance Exams",
    activePlan: "Law Entrance",
    lastActivity: "5 days ago",
    joinedDate: "Jun 10, 2025",
    status: "Suspended",
    planDate: "Jun 10, 2025",
    planExpiration: "Dec 10, 2025",
    completedQuizzes: 18,
    averageScore: 52,
    lastLogin: "Mar 7, 2026",
    role: "student",
    createdAt: "2025-06-10",
    updatedAt: "2026-03-07",
  },
  {
    id: "13",
    initials: "SA",
    name: "Sara Asllani",
    email: "sara.a@email.com",
    phone: "+355 69 567 890",
    category: "Semimatura",
    activePlan: "Free",
    lastActivity: "3 hours ago",
    joinedDate: "Jan 18, 2026",
    status: "Active",
    planDate: "—",
    planExpiration: "—",
    completedQuizzes: 7,
    averageScore: 68,
    lastLogin: "Mar 12, 2026",
    role: "student",
    createdAt: "2026-01-18",
    updatedAt: "2026-03-12",
  },
  {
    id: "14",
    initials: "TH",
    name: "Trim Hyseni",
    email: "trim.h@email.com",
    phone: "+383 44 678 901",
    category: "Entrance Exams",
    activePlan: "Economics Entrance",
    lastActivity: "8 hours ago",
    joinedDate: "Nov 25, 2025",
    status: "Active",
    planDate: "Feb 15, 2026",
    planExpiration: "Aug 15, 2026",
    completedQuizzes: 33,
    averageScore: 74,
    lastLogin: "Mar 12, 2026",
    role: "student",
    createdAt: "2025-11-25",
    updatedAt: "2026-03-12",
  },
  {
    id: "15",
    initials: "VP",
    name: "Valdrin Peci",
    email: "valdrin.p@email.com",
    phone: "+383 45 789 012",
    category: "Matura",
    activePlan: "Matura Pack",
    lastActivity: "1 day ago",
    joinedDate: "Aug 5, 2025",
    status: "Inactive",
    planDate: "Aug 5, 2025",
    planExpiration: "Feb 5, 2026",
    completedQuizzes: 29,
    averageScore: 62,
    lastLogin: "Mar 6, 2026",
    role: "student",
    createdAt: "2025-08-05",
    updatedAt: "2026-03-06",
  },
  {
    id: "16",
    initials: "ZM",
    name: "Zana Morina",
    email: "zana.m@email.com",
    phone: "+355 68 890 123",
    category: "Entrance Exams",
    activePlan: "Medicine Entrance",
    lastActivity: "6 hours ago",
    joinedDate: "Dec 12, 2025",
    status: "Active",
    planDate: "Dec 12, 2025",
    planExpiration: "Jun 12, 2026",
    completedQuizzes: 48,
    averageScore: 83,
    lastLogin: "Mar 12, 2026",
    role: "student",
    createdAt: "2025-12-12",
    updatedAt: "2026-03-12",
  },
];

// ─── Premium Subscriptions ────────────────────────────────────────────────────

export const mockSubscriptions: PremiumSubscription[] = [
  {
    id: "sub-1",
    userId: "1",
    initials: "AB",
    userName: "Arta Berisha",
    userEmail: "arta.berisha@email.co",
    product: "Matura",
    productColor: "#3B82F6",
    planType: "Yearly",
    startDate: "Jan 15, 2026",
    expiryDate: "Jan 15, 2027",
    status: "Active",
    payment: "Stripe",
    orderId: "ORD-2026-80458",
    amount: "€49.99",
    daysRemaining: 312,
  },
  {
    id: "sub-2",
    userId: "2",
    initials: "DH",
    userName: "Dritan Hoxha",
    userEmail: "dritan.hoxha@email.co",
    product: "Medicine Entrance Exam",
    productColor: "#06B6D4",
    planType: "One-time",
    startDate: "Feb 1, 2026",
    expiryDate: "Aug 1, 2026",
    status: "Active",
    payment: "Card",
    orderId: "ORD-2026-80471",
    amount: "€39.99",
    daysRemaining: 142,
  },
  {
    id: "sub-3",
    userId: "3",
    initials: "EK",
    userName: "Elona Krasniqi",
    userEmail: "elona.krasniqi@email.co",
    product: "Semimatura",
    productColor: "#8B5CF6",
    planType: "Monthly",
    startDate: "Dec 10, 2025",
    expiryDate: "Mar 12, 2026",
    status: "Active",
    payment: "PayPal",
    orderId: "ORD-2025-80385",
    amount: "€9.99",
    daysRemaining: 0,
    expiringWarning: true,
  },
  {
    id: "sub-4",
    userId: "4",
    initials: "FG",
    userName: "Fatos Gashi",
    userEmail: "fatos.gashi@email.co",
    product: "Law Entrance Exam",
    productColor: "#F59E0B",
    planType: "One-time",
    startDate: "Nov 5, 2025",
    expiryDate: "Mar 5, 2026",
    status: "Expired",
    payment: "Card",
    orderId: "ORD-2025-80342",
    amount: "€34.99",
  },
  {
    id: "sub-5",
    userId: "5",
    initials: "GS",
    userName: "Genta Shehu",
    userEmail: "genta.shehu@email.co",
    product: "Matura",
    productColor: "#3B82F6",
    planType: "Yearly",
    startDate: "Jan 20, 2026",
    expiryDate: "Jan 20, 2027",
    status: "Active",
    payment: "Stripe",
    orderId: "ORD-2026-80465",
    amount: "€49.99",
    daysRemaining: 314,
  },
  {
    id: "sub-6",
    userId: "6",
    initials: "IM",
    userName: "Ilir Maloku",
    userEmail: "ilir.maloku@email.co",
    product: "Economics Entrance Exam",
    productColor: "#F59E0B",
    planType: "Monthly",
    startDate: "Jan 1, 2026",
    expiryDate: "Feb 1, 2026",
    status: "Cancelled",
    payment: "PayPal",
    orderId: "ORD-2026-80452",
    amount: "€9.99",
  },
  {
    id: "sub-7",
    userId: "7",
    initials: "JB",
    userName: "Jetmira Beka",
    userEmail: "jetmira.beka@email.co",
    product: "Matura",
    productColor: "#3B82F6",
    planType: "Monthly",
    startDate: "Feb 15, 2026",
    expiryDate: "Mar 15, 2026",
    status: "Active",
    payment: "Card",
    orderId: "ORD-2026-80489",
    amount: "€9.99",
    daysRemaining: 3,
    expiringWarning: true,
  },
  {
    id: "sub-8",
    userId: "8",
    initials: "KR",
    userName: "Kushtrim Rexhep",
    userEmail: "kushtrim.rexhep@email.co",
    product: "Economics Entrance Exam",
    productColor: "#F59E0B",
    planType: "One-time",
    startDate: "Feb 15, 2026",
    expiryDate: "Aug 15, 2026",
    status: "Active",
    payment: "Manual",
    orderId: "ORD-2026-80491",
    amount: "€34.99",
    daysRemaining: 156,
  },
  {
    id: "sub-9",
    userId: "9",
    initials: "LM",
    userName: "Lindita Maliqi",
    userEmail: "lindita.maliqi@email.co",
    product: "Semimatura",
    productColor: "#8B5CF6",
    planType: "Yearly",
    startDate: "Sep 1, 2025",
    expiryDate: "Sep 1, 2026",
    status: "Active",
    payment: "Stripe",
    orderId: "ORD-2025-80298",
    amount: "€44.99",
    daysRemaining: 173,
  },
  {
    id: "sub-10",
    userId: "10",
    initials: "MT",
    userName: "Mergim Thaqi",
    userEmail: "mergim.thaqi@email.co",
    product: "Medicine Entrance Exam",
    productColor: "#06B6D4",
    planType: "One-time",
    startDate: "Mar 1, 2026",
    expiryDate: "Sep 1, 2026",
    status: "Active",
    payment: "Card",
    orderId: "ORD-2026-80501",
    amount: "€39.99",
    daysRemaining: 173,
  },
];
