import type { PremiumSubscription } from "@/types";

// 24 sample subscriptions:  Active: 20 | Expired: 2 | Cancelled: 2
// Expiring Soon (within 30d from Mar 16, 2026): 5  marked with expiringWarning: true
export const premiumSubscribersData: PremiumSubscription[] = [
  {
    id: "ps-001",
    userId: "u-001",
    initials: "AB",
    userName: "Aria Berisha",
    userEmail: "aria.berisha@email.co",
    product: "Matura",
    productColor: "#2f86d8",
    planType: "Yearly",
    startDate: "Jan 15, 2026",
    expiryDate: "Jan 15, 2027",
    status: "Active",
    payment: "Stripe",
    orderId: "083-2810-86418",
    amount: "€49.99",
  },
  {
    id: "ps-002",
    userId: "u-002",
    initials: "DH",
    userName: "Dritan Hoxha",
    userEmail: "dritan.hoxha@email.mo",
    product: "Medicine Entrance Exam",
    productColor: "#3b9b81",
    planType: "One-time",
    startDate: "Feb 1, 2026",
    expiryDate: "Aug 15, 2026",
    status: "Active",
    payment: "Card",
    orderId: "083-2810-86471",
    amount: "€29.99",
  },
  {
    id: "ps-003",
    userId: "u-003",
    initials: "EK",
    userName: "Elona Krasniqi",
    userEmail: "elona.krasniqi@email.co",
    product: "Semimatura",
    productColor: "#748ccc",
    planType: "Monthly",
    startDate: "Feb 15, 2026",
    expiryDate: "Mar 19, 2026",
    status: "Active",
    payment: "PayPal",
    orderId: "083-3615-86189",
    amount: "€9.99",
    daysRemaining: 3,
    expiringWarning: true,
  },
  {
    id: "ps-004",
    userId: "u-004",
    initials: "FG",
    userName: "Falos Gashi",
    userEmail: "falos.gashi@email.co",
    product: "Live Entrance Exam",
    productColor: "#3aa86e",
    planType: "One-time",
    startDate: "Nov 5, 2025",
    expiryDate: "Mar 5, 2026",
    status: "Expired",
    payment: "Card",
    orderId: "083-2625-86342",
    amount: "€29.99",
  },
  {
    id: "ps-005",
    userId: "u-005",
    initials: "GS",
    userName: "Genta Shehu",
    userEmail: "genta.shehu@email.mo",
    product: "Matura",
    productColor: "#2f86d8",
    planType: "Yearly",
    startDate: "Jan 20, 2026",
    expiryDate: "Jan 29, 2027",
    status: "Active",
    payment: "Stripe",
    orderId: "083-2810-86402",
    amount: "€49.99",
  },
  {
    id: "ps-006",
    userId: "u-006",
    initials: "IM",
    userName: "Ilir Maloku",
    userEmail: "ilir.maloku@email.com",
    product: "Economics Entrance Exam",
    productColor: "#3b9b81",
    planType: "Monthly",
    startDate: "Jan 1, 2026",
    expiryDate: "Feb 1, 2026",
    status: "Cancelled",
    payment: "PayPal",
    orderId: "083-2810-86881",
    amount: "€9.99",
  },
  {
    id: "ps-007",
    userId: "u-007",
    initials: "JB",
    userName: "Jetmira Beka",
    userEmail: "jetmira.beka@email.co",
    product: "Matura",
    productColor: "#2f86d8",
    planType: "Monthly",
    startDate: "Feb 15, 2026",
    expiryDate: "Mar 24, 2026",
    status: "Active",
    payment: "Card",
    orderId: "083-2816-86488",
    amount: "€9.99",
    daysRemaining: 8,
    expiringWarning: true,
  },
  {
    id: "ps-008",
    userId: "u-008",
    initials: "KR",
    userName: "Kushtrim Rexhepi",
    userEmail: "kushtrim.rexhepi@email.co",
    product: "Economics Entrance Exam",
    productColor: "#3b9b81",
    planType: "One-time",
    startDate: "Feb 15, 2026",
    expiryDate: "Aug 15, 2026",
    status: "Active",
    payment: "Manual",
    orderId: "083-2810-86995",
    amount: "€29.99",
  },
  {
    id: "ps-009",
    userId: "u-009",
    initials: "LM",
    userName: "Lindita Maligi",
    userEmail: "lindita.maligi@email.co",
    product: "Semimatura",
    productColor: "#748ccc",
    planType: "Yearly",
    startDate: "Sep 1, 2025",
    expiryDate: "Sep 1, 2026",
    status: "Active",
    payment: "Stripe",
    orderId: "083-2816-86049",
    amount: "€49.99",
  },
  {
    id: "ps-010",
    userId: "u-010",
    initials: "MT",
    userName: "Mergim Thagi",
    userEmail: "mergim.thagi@email.co",
    product: "Medicine Entrance Exam",
    productColor: "#3b9b81",
    planType: "One-time",
    startDate: "Mar 1, 2026",
    expiryDate: "Sep 1, 2026",
    status: "Active",
    payment: "Card",
    orderId: "083-3645-86942",
    amount: "€29.99",
  },
  {
    id: "ps-011",
    userId: "u-011",
    initials: "AL",
    userName: "Albana Leka",
    userEmail: "albana.leka@email.co",
    product: "Matura",
    productColor: "#2f86d8",
    planType: "Yearly",
    startDate: "Mar 1, 2026",
    expiryDate: "Mar 1, 2027",
    status: "Active",
    payment: "Stripe",
    orderId: "083-2810-87001",
    amount: "€49.99",
  },
  {
    id: "ps-012",
    userId: "u-012",
    initials: "BV",
    userName: "Besnik Vora",
    userEmail: "besnik.vora@email.co",
    product: "Semimatura",
    productColor: "#748ccc",
    planType: "Monthly",
    startDate: "Jan 15, 2026",
    expiryDate: "Feb 15, 2026",
    status: "Cancelled",
    payment: "Card",
    orderId: "083-2810-87002",
    amount: "€9.99",
  },
  {
    id: "ps-013",
    userId: "u-013",
    initials: "DH",
    userName: "Donika Halimi",
    userEmail: "donika.halimi@email.co",
    product: "Live Entrance Exam",
    productColor: "#3aa86e",
    planType: "One-time",
    startDate: "Feb 1, 2026",
    expiryDate: "Aug 1, 2026",
    status: "Active",
    payment: "PayPal",
    orderId: "083-2810-87003",
    amount: "€29.99",
  },
  {
    id: "ps-014",
    userId: "u-014",
    initials: "ES",
    userName: "Ermal Sefa",
    userEmail: "ermal.sefa@email.co",
    product: "Matura",
    productColor: "#2f86d8",
    planType: "Monthly",
    startDate: "Nov 1, 2025",
    expiryDate: "Mar 8, 2026",
    status: "Expired",
    payment: "Stripe",
    orderId: "083-2810-87004",
    amount: "€9.99",
  },
  {
    id: "ps-015",
    userId: "u-015",
    initials: "FC",
    userName: "Fatmira Cela",
    userEmail: "fatmira.cela@email.co",
    product: "Economics Entrance Exam",
    productColor: "#3b9b81",
    planType: "Yearly",
    startDate: "Jun 1, 2025",
    expiryDate: "Jun 1, 2026",
    status: "Active",
    payment: "Card",
    orderId: "083-2810-87005",
    amount: "€49.99",
  },
  {
    id: "ps-016",
    userId: "u-016",
    initials: "GP",
    userName: "Gentian Pula",
    userEmail: "gentian.pula@email.co",
    product: "Medicine Entrance Exam",
    productColor: "#3b9b81",
    planType: "One-time",
    startDate: "Nov 10, 2025",
    expiryDate: "May 10, 2026",
    status: "Active",
    payment: "Manual",
    orderId: "083-2810-87006",
    amount: "€29.99",
  },
  {
    id: "ps-017",
    userId: "u-017",
    initials: "HD",
    userName: "Hana Deda",
    userEmail: "hana.deda@email.co",
    product: "Semimatura",
    productColor: "#748ccc",
    planType: "Yearly",
    startDate: "Aug 5, 2025",
    expiryDate: "Aug 5, 2026",
    status: "Active",
    payment: "Stripe",
    orderId: "083-2810-87007",
    amount: "€49.99",
  },
  {
    id: "ps-018",
    userId: "u-018",
    initials: "IN",
    userName: "Ilva Nushi",
    userEmail: "ilva.nushi@email.co",
    product: "Matura",
    productColor: "#2f86d8",
    planType: "Monthly",
    startDate: "Mar 2, 2026",
    expiryDate: "Apr 2, 2026",
    status: "Active",
    payment: "PayPal",
    orderId: "083-2810-87008",
    amount: "€9.99",
    daysRemaining: 17,
    expiringWarning: true,
  },
  {
    id: "ps-019",
    userId: "u-019",
    initials: "JB",
    userName: "Julian Brahja",
    userEmail: "julian.brahja@email.co",
    product: "Live Entrance Exam",
    productColor: "#3aa86e",
    planType: "Yearly",
    startDate: "Jan 1, 2026",
    expiryDate: "Jan 1, 2027",
    status: "Active",
    payment: "Card",
    orderId: "083-2810-87009",
    amount: "€49.99",
  },
  {
    id: "ps-020",
    userId: "u-020",
    initials: "KB",
    userName: "Klea Basha",
    userEmail: "klea.basha@email.co",
    product: "Semimatura",
    productColor: "#748ccc",
    planType: "One-time",
    startDate: "Oct 1, 2025",
    expiryDate: "Apr 8, 2026",
    status: "Active",
    payment: "Stripe",
    orderId: "083-2810-87010",
    amount: "€29.99",
    daysRemaining: 23,
    expiringWarning: true,
  },
  {
    id: "ps-021",
    userId: "u-021",
    initials: "LH",
    userName: "Lirim Hasa",
    userEmail: "lirim.hasa@email.co",
    product: "Matura",
    productColor: "#2f86d8",
    planType: "Monthly",
    startDate: "Mar 12, 2026",
    expiryDate: "Apr 12, 2026",
    status: "Active",
    payment: "Card",
    orderId: "083-2810-87011",
    amount: "€9.99",
    daysRemaining: 27,
    expiringWarning: true,
  },
  {
    id: "ps-022",
    userId: "u-022",
    initials: "MD",
    userName: "Mimoza Doci",
    userEmail: "mimoza.doci@email.co",
    product: "Economics Entrance Exam",
    productColor: "#3b9b81",
    planType: "Yearly",
    startDate: "Jul 10, 2025",
    expiryDate: "Jul 10, 2026",
    status: "Active",
    payment: "PayPal",
    orderId: "083-2810-87012",
    amount: "€49.99",
  },
  {
    id: "ps-023",
    userId: "u-023",
    initials: "NS",
    userName: "Nora Shpati",
    userEmail: "nora.shpati@email.co",
    product: "Medicine Entrance Exam",
    productColor: "#3b9b81",
    planType: "Monthly",
    startDate: "Dec 1, 2025",
    expiryDate: "Jun 1, 2026",
    status: "Active",
    payment: "Manual",
    orderId: "083-2810-87013",
    amount: "€9.99",
  },
  {
    id: "ps-024",
    userId: "u-024",
    initials: "OK",
    userName: "Orges Kaziu",
    userEmail: "orges.kaziu@email.co",
    product: "Matura",
    productColor: "#2f86d8",
    planType: "Yearly",
    startDate: "Apr 5, 2025",
    expiryDate: "Apr 20, 2026",
    status: "Active",
    payment: "Stripe",
    orderId: "083-2810-87014",
    amount: "€49.99",
  },
];
