import type { UserStatus } from "@/types";

export type UserManagementUser = {
  id: string;
  initials: string;
  name: string;
  email: string;
  preferredCategory: "Matura" | "Semimatura" | "Entrance Exams";
  type: "Student" | "Premium";
  activePlan: string;
  lastActivity: string;
  joinedDate: string;
  status: UserStatus;
};

export const userManagementUsers: UserManagementUser[] = [
  {
    id: "u1",
    initials: "AB",
    name: "Arta Berisha",
    email: "arta.b@email.com",
    preferredCategory: "Matura",
    type: "Student",
    activePlan: "Matura Pack",
    lastActivity: "2 hours ago",
    joinedDate: "Sep 12, 2025",
    status: "Active",
  },
  {
    id: "u2",
    initials: "DH",
    name: "Dritan Hoxha",
    email: "dritan.h@email.com",
    preferredCategory: "Entrance Exams",
    type: "Premium",
    activePlan: "Medicine Entrance",
    lastActivity: "5 hours ago",
    joinedDate: "Oct 3, 2025",
    status: "Active",
  },
  {
    id: "u3",
    initials: "EK",
    name: "Elona Krasniqi",
    email: "elona.k@email.com",
    preferredCategory: "Semimatura",
    type: "Premium",
    activePlan: "Semimatura Pack",
    lastActivity: "1 day ago",
    joinedDate: "Aug 20, 2025",
    status: "Active",
  },
  {
    id: "u4",
    initials: "FG",
    name: "Fatos Gashi",
    email: "fatos.g@email.com",
    preferredCategory: "Entrance Exams",
    type: "Premium",
    activePlan: "Law Entrance",
    lastActivity: "3 days ago",
    joinedDate: "Jul 15, 2025",
    status: "Suspended",
  },
  {
    id: "u5",
    initials: "GS",
    name: "Genta Shehu",
    email: "genta.s@email.com",
    preferredCategory: "Matura",
    type: "Premium",
    activePlan: "Matura Pack",
    lastActivity: "6 hours ago",
    joinedDate: "Nov 8, 2025",
    status: "Active",
  },
  {
    id: "u6",
    initials: "IM",
    name: "Ilir Maloku",
    email: "ilir.m@email.com",
    preferredCategory: "Entrance Exams",
    type: "Student",
    activePlan: "Free",
    lastActivity: "7 days ago",
    joinedDate: "Dec 1, 2025",
    status: "Inactive",
  },
  {
    id: "u7",
    initials: "JB",
    name: "Jetmira Beka",
    email: "jetmira.b@email.com",
    preferredCategory: "Matura",
    type: "Student",
    activePlan: "Free",
    lastActivity: "12 hours ago",
    joinedDate: "Jan 5, 2026",
    status: "Active",
  },
  {
    id: "u8",
    initials: "KR",
    name: "Kushtrim Rexhep",
    email: "kushtrim.r@email.com",
    preferredCategory: "Entrance Exams",
    type: "Premium",
    activePlan: "Economics Entrance",
    lastActivity: "1 day ago",
    joinedDate: "Oct 22, 2025",
    status: "Active",
  },
  {
    id: "u9",
    initials: "LM",
    name: "Lindita Maliqi",
    email: "lindita.m@email.com",
    preferredCategory: "Semimatura",
    type: "Premium",
    activePlan: "Semimatura Pack",
    lastActivity: "4 hours ago",
    joinedDate: "Sep 30, 2025",
    status: "Active",
  },
  {
    id: "u10",
    initials: "MT",
    name: "Mergim Thaqi",
    email: "mergim.t@email.com",
    preferredCategory: "Entrance Exams",
    type: "Premium",
    activePlan: "Medicine Entrance",
    lastActivity: "30 min ago",
    joinedDate: "Feb 14, 2026",
    status: "Active",
  },
  {
    id: "u11",
    initials: "NB",
    name: "Nora Berisha",
    email: "nora.b@email.com",
    preferredCategory: "Matura",
    type: "Premium",
    activePlan: "Matura Pack",
    lastActivity: "1 hour ago",
    joinedDate: "Dec 12, 2025",
    status: "Active",
  },
  {
    id: "u12",
    initials: "PR",
    name: "Petrit Rrahmani",
    email: "petrit.r@email.com",
    preferredCategory: "Entrance Exams",
    type: "Student",
    activePlan: "Free",
    lastActivity: "3 days ago",
    joinedDate: "Nov 10, 2025",
    status: "Inactive",
  },
  {
    id: "u13",
    initials: "QN",
    name: "Qendresa Nika",
    email: "qendresa.n@email.com",
    preferredCategory: "Semimatura",
    type: "Premium",
    activePlan: "Semimatura Pack",
    lastActivity: "2 days ago",
    joinedDate: "Jan 20, 2026",
    status: "Suspended",
  },
  {
    id: "u14",
    initials: "RA",
    name: "Rinor Ahmeti",
    email: "rinor.a@email.com",
    preferredCategory: "Matura",
    type: "Student",
    activePlan: "Free",
    lastActivity: "6 days ago",
    joinedDate: "Oct 28, 2025",
    status: "Active",
  },
  {
    id: "u15",
    initials: "SV",
    name: "Sara Veliu",
    email: "sara.v@email.com",
    preferredCategory: "Entrance Exams",
    type: "Premium",
    activePlan: "Law Entrance",
    lastActivity: "5 hours ago",
    joinedDate: "Feb 5, 2026",
    status: "Active",
  },
  {
    id: "u16",
    initials: "TZ",
    name: "Trim Zeka",
    email: "trim.z@email.com",
    preferredCategory: "Matura",
    type: "Premium",
    activePlan: "Matura Pack",
    lastActivity: "9 hours ago",
    joinedDate: "Aug 18, 2025",
    status: "Active",
  },
];
